"""empty message

Revision ID: a4b6fdfc1683
Revises: 9d07829ca9a6
Create Date: 2024-01-25 15:34:04.349598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b6fdfc1683'
down_revision = '9d07829ca9a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('update_date')

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_column('update_date')

    # ### end Alembic commands ###
